1126/fixes package validation error with dialect
frictionlessdata/frictionless-py pull request #1137
Opened 2022-06-15 13:24 UTC by shashigharti

* Added fix for the bug in the package class while using with dialect
* Added tests
- fixes #1126

2022-06-15 13:33 UTC, shashigharti commented
@roll it is ready for the review!

2022-06-16 06:03 UTC, roll requested changes

2022-06-16 06:03 UTC, roll commented on frictionless/package/package.py
> +        self.setinitial("dialect", dialect)
Hi @shashigharti, sorry that's in v4 is kinda confusing (will be improved in v5) but can you please store the dialect as `self.__dialect = dialect` the same way as detector (you can see it under the extra comment in the arg list) -- the reason is that dialect is not a part of the data package spec (the same as detector) so we should not store it in the package descriptor

2022-06-16 06:04 UTC, roll commented on frictionless/package/package.py
> +        self.setinitial("dialect", dialect)
The PR looks really well btw :+1:

2022-06-20 03:27 UTC, shashigharti commented
Thank you @roll!  It is ready for the review.

2022-06-20 07:57 UTC, roll approved these changes
Thanks!

2022-06-20 07:57 UTC, merged