1174 add default innerpath
frictionlessdata/frictionless-py pull request #1179
Opened 2022-07-15 08:03 UTC by kagawa0710

- fixes #1174 

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

When no innerpath argument is given, the existence of data package.json and datapackage.yaml is checked and given.

2022-07-16 04:00 UTC, augusto-herrmann requested changes
Good job, @kagawa0710!

I have run the tests locally and they pass. I suggest a little change to avoid some repetition in code and also catch the case where there is a `datapackage.yml` file.

2022-07-16 04:00 UTC, augusto-herrmann commented on frictionless/helpers.py
> +                innerpath = "datapackage.json"
```suggestion
            if innerpath == "":
                innerpath = "datapackage.json"
                extensions = ("json", "yaml", "yml")
                default_names = (f"datapackage.{ext}" for ext in extensions)
                for name in default_names:
                    if os.path.isfile(os.path.join(tempdir, name)):
                        innerpath = name
                        break
```

How about we change it like this to avoid some repetition? This also passes the test and has the same effect (plus adds a heuristic for also finding `.yml`).

2022-07-16 04:00 UTC, augusto-herrmann commented on frictionless/package/package.py
> +            Default: datapackage.json or datapackage.yaml
```suggestion
            Default: datapackage.json, datapackage.yaml or datapackage.yml
```

2022-07-16 04:26 UTC, kagawa0710 commented
@augusto-herrmann 
Thanks for the suggestion.I think it's better this way too!
Commit accepted.

2022-07-16 04:27 UTC, kagawa0710 commented on frictionless/helpers.py
> +                innerpath = "datapackage.json"
nice!!

2022-07-16 04:46 UTC, augusto-herrmann approved these changes
Excellent. ありがとうございました, @kagawa0710!

2022-07-18 12:24 UTC, roll approved these changes
Thanks!

2022-07-18 12:24 UTC, merged