Added convert command
frictionlessdata/frictionless-py pull request #1195
Opened 2022-07-18 10:52 UTC by shashigharti

Added convert command
Added tests

- fixes #1170

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

2022-07-18 10:53 UTC, shashigharti commented
@roll it is ready for review!

2022-07-18 14:07 UTC, roll requested changes
It's a good start and we can extend it to support all the metadata types

2022-07-18 14:07 UTC, roll commented on frictionless/program/convert.py
> +    # Initialize Package
Sorry @shashigharti,

the initial issue description was quite confusing as a I see now. What I meant that we can have metadata conversion feature actually for all types of metadata (package/resource/schema/etc).

So if we do something like this:

```python
 try:
        metadata_type = Detector.detect_descriptor(source)
        if metadata_type == 'package':
          metadata = Package.from_descriptor(source)
        elif metadata_type == 'resource':
          metadata = Resource.from_description(source)
        # and more types
    except Exception as exception:
        typer.secho(str(exception), err=True, fg=typer.colors.RED, bold=True)
        raise typer.Exit(1)
```

Then we can do:

```python
if yaml:
        content = metadata.to_yaml(path)
        typer.secho(content)
        raise typer.Exit()
```

2022-07-18 14:07 UTC, roll commented on frictionless/program/convert.py
> +    if yaml:
Let's also support `json`. For example, use case:

```
frictionless convert schema.yaml --json
```

2022-07-18 14:07 UTC, roll commented on frictionless/program/convert.py
> +        message = 'Providing package "source" is required'
Providing "source" is required (as it can be other types not only package)

2022-07-18 14:07 UTC, roll commented on frictionless/program/convert.py
> +    if er_diagram:
This one will work only for `metadata_type == 'package'`

2022-07-19 14:48 UTC, shashigharti commented on frictionless/program/convert.py
> +    # Initialize Package
It only detects resource and package only. 
metadata_type = Detector.detect_descriptor(source)

what do you suggest?

2022-07-21 09:09 UTC, shashigharti commented
@roll Thank you! I have made the changes and it is ready for the review.

2022-07-22 05:42 UTC, roll approved these changes
Great thanks!

2022-07-22 05:42 UTC, merged

2022-07-22 05:46 UTC, roll commented
Thanks for adding those convert tests for different metadata types -- it will be really useful to catch regressions :+1: