Fixed dialect for extract
frictionlessdata/frictionless-py pull request #1264
Opened 2022-10-14 06:27 UTC by shashigharti

- Added bug fix for CSV delimiter. Now it does not change the delimiter to default ","
- fixes #1009

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

2022-10-14 06:34 UTC, shashigharti commented
@roll this is ready for review

2022-10-26 07:59 UTC, roll requested changes
Thanks, @shashigharti,

It's a really great iteration to better understand the problem but I'm afraid we need to think twice about this. The problem here is that we're stepping into a really big area of data conversion when we have input options and output options. 

I know that it was in the initial feature request (and it's not a bug btw) but I started thinking more and more about this and it feels that first we will keep the delimiter than using the same logic we need to keep the header rows (e.g. starting from row 2) etc. So basically, it will break the idea of the `extract` actions as a normalization function.

I would suggest reconsidering the implementation and implement it as a new feature that doesn't affect current behavirou. For example, what if we keep everything existent as it is BUT add a new flag like `keep-delimiter` for `program.extract` that will implement the feature request?

WDYT?

2022-10-26 07:59 UTC, roll commented on tests/program/test_extract.py
> +        'extract data/issue-1009-comma.csv --dialect \'{"delimiter": ","}\' --csv',
Unfortunately, we can't do something like this. `extract --dialect` means "specify a dialect of the input file" but not for the output one.

2022-10-26 08:35 UTC, shashigharti commented
> Thank you! I agree with that. I will try to change the implementation considering your suggestions.

2022-11-21 11:09 UTC, shashigharti commented
@roll thank you!, I have revised the code.  And now it will retain the delimiter if dialect info has been specified in params and --keep-params is set to true.

It is ready for the review.

2022-11-23 04:56 UTC, roll approved these changes
Amazing! Thanks!

2022-11-23 04:57 UTC, merged

2022-11-23 07:17 UTC, aborruso commented
thank you very much @shashigharti and @roll