Fix to set header to false
frictionlessdata/frictionless-py pull request #1523
Opened 2023-06-12 08:20 UTC by shashigharti

- fixes #1513

---

Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

2023-06-12 09:37 UTC, shashigharti commented
@roll it is ready for review. Thank you!. 

I have few concerns regarding the test that I have added. If `target` is already a table resource, then there is no way to set the `dialect` through write function. For example this does not work:

```
def test_yaml_parser_write_skip_header(tmpdir):
    dialect = Dialect.from_descriptor({"header": False})
    target = TableResource(path=str(tmpdir.join("table.yaml")))  # I did not set the dialect here
    with TableResource(path="data/table.csv") as resource:
        assert resource.header == ["id", "name"]
        resource.write_table(target, dialect=dialect) # This does not get applied
        assert target.read_rows() == [
            {"field1": 1, "field2": "english"},
            {"field1": 2, "field2": "中国人"},
        ]
```

2023-06-13 10:00 UTC, roll requested changes
Amazing work @shashigharti!

Just a small request change regarding typing

2023-06-13 10:00 UTC, roll commented on tests/formats/excel/parsers/test_xls.py
> +        assert resource.header == ["value11", "value12"]  # type: ignore
If you use `TableResource` you don't need "type: ignore" here and in other tests

2023-06-14 05:44 UTC, shashigharti commented on tests/formats/excel/parsers/test_xls.py
> +        assert resource.header == ["value11", "value12"]  # type: ignore
Thanks! @roll I had tried that I don't have to use `# type: ignore` , however I had faced another issue, the dialect does not get set using write_table [here](https://github.com/frictionlessdata/framework/blob/main/frictionless/resources/table.py#L454)
, so I used `string` path instead.
```
def test_xls_parser_write_skip_header(tmpdir):
    control = formats.ExcelControl(sheet="sheet")
    dialect = Dialect.from_descriptor({"header": False})
    data = b"header1,header2\nvalue11,value12\nvalue21,value22"
    target = TableResource(path=str(tmpdir.join("table.xls")), control=control)
    with TableResource(data=data, format="csv") as resource:
        assert resource.header == ["header1", "header2"]
        resource.write_table(target, dialect=dialect)
    with target:
        assert target.header == ["value11", "value12"]
```

2023-06-14 12:38 UTC, roll commented on tests/formats/excel/parsers/test_xls.py
> +        assert resource.header == ["value11", "value12"]  # type: ignore
@shashigharti I mean just for reading:
```
with TableResource(data=data, format="csv") as resource:
        assert resource.header == ["header1", "header2"]
        resource.write_table(target, dialect=dialect, control=control)
    with TableResource(path=str(tmpdir.join("table.xls")), control=control) as resource:
        assert resource.header == ["value11", "value12"]
```

Or shall we fix `table.write_table` to support dialect?

2023-06-15 07:18 UTC, shashigharti commented on tests/formats/excel/parsers/test_xls.py
> +        assert resource.header == ["value11", "value12"]  # type: ignore
Thanks @roll I have made the changes.

2023-06-15 07:23 UTC, shashigharti commented
Thanks! @roll, I have made the changes. 

I tried this also to update other params along with dialect but I got `path is not safe` error:

`resource = resource.to_copy(control=control, **options)`

2023-06-15 07:45 UTC, roll approved these changes
Thanks!

2023-06-15 07:45 UTC, merged